#Grove_Example1:
#    name: Grove_Example
#    construct_arg_list:
#        pinsda: 4
#        pinscl: 5
GroveRelay:
    name: Grove_Relay
    construct_arg_list:
        pin: 14
#GroveRelay2:
#    name: Grove-Dry-Reed Relay
#    construct_arg_list:
#        pin: 14        
#GroveRelay3:
#    name: Grove-Solid State Relay
#    construct_arg_list:
#        pin: 14        
#GroveRelay4:
#    name: Grove - SPDT Relay(30A)
#    construct_arg_list:
#        pin: 14        
#GroveAccMMA7660:
#    name: Grove-3Axis Digital Acc(\u00b11.5g)
#    construct_arg_list:
#        pinsda: 4
#        pinscl: 5   
#GroveBaroBMP085:
#    name: Grove-Barometer(BMP085)
#    construct_arg_list:
#        pinsda: 4
#        pinscl: 5   
#Grove_DigitalLight1:
#    name: Grove-Digital Light
#    construct_arg_list:
#        pinsda: 4
#        pinscl: 5
#Grove_Gyro_ITG3200:
#    name: Grove-3-Axis Digital Gyro
#    construct_arg_list:
#        pinsda: 4
#        pinscl: 5
#GroveMoisture:
#    name: Grove-Moisture
#    construct_arg_list:
#        pin: 17
GroveRotary:
    name: Grove-Rotary Angle Sensor
    construct_arg_list:
        pin: 17
##GroveTempHum111:
##    name: Grove-Temperature&Humidity
##    construct_arg_list:
##        pin: 14
#GroveIRDistanceInterrupter111:
#    name: Grove-IR Distance Interrupter
#    construct_arg_list:
#        pin: 14
#GroveButton:
#    name: Grove-Button
#    construct_arg_list:
#        pin: 0
##GroveButton1:
##    name: Grove-Button
##    construct_arg_list:
##        pin: 12
#GroveMagSw1:
#    name: Grove-Magnetic Switch
#    construct_arg_list:
#        pin: 12
#GroveCompass111:
#    name: Grove-3Axis Compass
#    construct_arg_list:
#        pinsda: 4
#        pinscl: 5
GroveMultiChannelGas111:
    name: Grove-Multichannel Gas Sensor
    construct_arg_list:
        pinsda: 4
        pinscl: 5
GroveSpeaker111:
    name: Grove-Speaker
    construct_arg_list:
        pin: 13
GroveLed:
    name: Grove-WS2812 LED Strip 60
    construct_arg_list:
        pin: 12
#GroveServo1:
#    name: Grove-Servo
#    construct_arg_list:
#        pin: 12

