Grove_Example1:
    name: Grove_Example
    construct_arg_list:
        pinsda: 4
        pinscl: 5
#GroveRelay:
#    name: Grove_Relay
#    construct_arg_list:
#        pin: 14
GroveAccMMA7660:
    name: Grove-3Axis Digital Acc(\u00b11.5g)
    construct_arg_list:
        pinsda: 4
        pinscl: 5   
GroveBaroBMP085:
    name: Grove-Barometer(BMP085)
    construct_arg_list:
        pinsda: 4
        pinscl: 5   
Grove_DigitalLight1:
    name: Grove-Digital Light
    construct_arg_list:
        pinsda: 4
        pinscl: 5
Grove_Gyro_ITG3200:
    name: Grove-3-Axis Digital Gyro
    construct_arg_list:
        pinsda: 4
        pinscl: 5
GroveMoisture:
    name: Grove-Moisture
    construct_arg_list:
        pin: 17
#GroveTempHum111:
#    name: Grove-Temperature&Humidity
#    construct_arg_list:
#        pin: 14
GroveIRDistanceInterrupter111:
    name: Grove-IR Distance Interrupter
    construct_arg_list:
        pin: 14

